#!/usr/bin/env node
/**
 * VetCare Memory Logger
 * ─────────────────────
 * One-command structured logging to memory files.
 * Called by: agents, post-commit hook, developers
 *
 * Usage:
 *   node backend/scripts/log-memory.js bug   "DEPLOY-010" "Title" "Symptom" "Root Cause" "Fix" "Rule"
 *   node backend/scripts/log-memory.js lesson "LESSON-034" "Title" "Context" "Lesson" "Apply to"
 *   node backend/scripts/log-memory.js feature "Feature Name" "done|planned|dropped" "Description"
 *   node backend/scripts/log-memory.js research "Topic" "Finding" "Source/Context"
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const MEMORIES = path.join(ROOT, 'memories', 'repo');

const RED    = '\x1b[31m';
const GREEN  = '\x1b[32m';
const CYAN   = '\x1b[36m';
const YELLOW = '\x1b[33m';
const RESET  = '\x1b[0m';

function appendToFile(filePath, content) {
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, `# Auto-generated memory log\n\n`, 'utf8');
  }
  fs.appendFileSync(filePath, content, 'utf8');
}

function timestamp() {
  return new Date().toISOString().replace('T', ' ').substring(0, 16);
}

const [,, type, ...args] = process.argv;

if (!type) {
  console.log(`${CYAN}VetCare Memory Logger${RESET}
  
Usage:
  ${YELLOW}bug${RESET}      <ID> <Title> <Symptom> <Root Cause> <Fix> <Rule>
  ${YELLOW}lesson${RESET}   <ID> <Title> <Context> <Lesson> <Apply-to>
  ${YELLOW}feature${RESET}  <Name> <done|planned|dropped> <Description>
  ${YELLOW}research${RESET} <Topic> <Finding> <Context>
  ${YELLOW}note${RESET}     <Title> <Content>

Examples:
  node backend/scripts/log-memory.js bug "DEPLOY-010" "DB timeout" "Pool hung" "Added retry" "Always use connectionTimeoutMillis"
  node backend/scripts/log-memory.js lesson "LESSON-034" "OOM on Render" "Vite built 1.5MB chunk" "Use manualChunks" "All future vite configs"
  node backend/scripts/log-memory.js feature "Hospital Network" "done" "Multi-hospital network management with consent flow"
`);
  process.exit(0);
}

switch (type.toLowerCase()) {
  case 'bug': {
    const [id, title, symptom, rootCause, fix, rule] = args;
    if (!id || !title) { console.error(`${RED}✗ bug requires: ID Title Symptom RootCause Fix Rule${RESET}`); process.exit(1); }
    
    const entry = `
### ${id} - ${title}
- **Logged:** ${timestamp()}
- **Symptom:** ${symptom || 'Not specified'}
- **Root Cause:** ${rootCause || 'Not specified'}
- **Fix:** ${fix || 'Not specified'}
- **Rule:** ${rule || 'Not specified'}

`;
    const filePath = path.join(MEMORIES, 'past-bugs.md');
    appendToFile(filePath, entry);
    console.log(`${GREEN}✓ Bug logged to past-bugs.md: ${id} - ${title}${RESET}`);
    break;
  }

  case 'lesson': {
    const [id, title, context, lesson, applyTo] = args;
    if (!id || !title) { console.error(`${RED}✗ lesson requires: ID Title Context Lesson Apply-to${RESET}`); process.exit(1); }
    
    const entry = `
### ${id} - ${title}
- **Logged:** ${timestamp()}
- **Context:** ${context || 'Not specified'}
- **Lesson:** ${lesson || 'Not specified'}
- **Apply to:** ${applyTo || 'All future work'}

`;
    const filePath = path.join(MEMORIES, 'lessons.md');
    appendToFile(filePath, entry);
    console.log(`${GREEN}✓ Lesson logged to lessons.md: ${id} - ${title}${RESET}`);
    break;
  }

  case 'feature': {
    const [name, status, description] = args;
    if (!name) { console.error(`${RED}✗ feature requires: Name Status Description${RESET}`); process.exit(1); }
    
    const icon = status === 'done' ? '✅' : status === 'dropped' ? '❌' : '⚠️';
    const entry = `
### ${icon} ${name}
- **Logged:** ${timestamp()}
- **Status:** ${status || 'planned'}
- **Description:** ${description || 'Not specified'}

`;
    const filePath = path.join(MEMORIES, 'feature-tracker.md');
    appendToFile(filePath, entry);
    console.log(`${GREEN}✓ Feature logged to feature-tracker.md: ${name}${RESET}`);
    break;
  }

  case 'research': {
    const [topic, finding, context] = args;
    if (!topic) { console.error(`${RED}✗ research requires: Topic Finding Context${RESET}`); process.exit(1); }
    
    const filePath = path.join(MEMORIES, 'research-log.md');
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, `# VetCare Research & Analysis Log\n\n> Auto-generated by log-memory.js and post-commit hook.\n\n---\n\n`, 'utf8');
    }
    const entry = `## ${topic}
- **Logged:** ${timestamp()}
- **Finding:** ${finding || 'Not specified'}
- **Context:** ${context || 'Not specified'}

---

`;
    fs.appendFileSync(filePath, entry, 'utf8');
    console.log(`${GREEN}✓ Research logged to research-log.md: ${topic}${RESET}`);
    break;
  }

  case 'note': {
    const [title, content] = args;
    if (!title) { console.error(`${RED}✗ note requires: Title Content${RESET}`); process.exit(1); }
    
    const filePath = path.join(MEMORIES, 'notes.md');
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, `# VetCare Notes & Ad-hoc Logs\n\n> Auto-generated. Agent-readable.\n\n---\n\n`, 'utf8');
    }
    const entry = `## ${title}
- **Logged:** ${timestamp()}
- **Content:** ${content || 'Not specified'}

---

`;
    fs.appendFileSync(filePath, entry, 'utf8');
    console.log(`${GREEN}✓ Note logged to notes.md: ${title}${RESET}`);
    break;
  }

  default:
    console.error(`${RED}✗ Unknown type: ${type}. Use: bug, lesson, feature, research, note${RESET}`);
    process.exit(1);
}
