-- Migration: 022_master_data_tables.sql
-- Description: Admin-editable master data for species, breeds, animal class terms,
--              marketplace categories, and marketplace conditions - replaces the
--              hardcoded TypeScript arrays in frontend/src/constants/speciesBreeds.ts
--              and Marketplace.tsx's CATEGORY_KEYS/condition options, which had no
--              admin CRUD UI at all (any change required a code edit + redeploy).
-- Depends on: none (species/breed/category/condition are free-standing reference data;
--             animals.species, marketplace_listings.species/category/condition/animal_class
--             remain plain VARCHAR columns - NOT converted to FKs, to avoid a data
--             migration risk on existing rows; identity is matched by the `code`/`value`
--             string, exactly as today).

-- ============================================================
-- 1. SPECIES
-- ============================================================
CREATE TABLE IF NOT EXISTS master_species (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(50) UNIQUE NOT NULL,
  label VARCHAR(100) NOT NULL,
  icon VARCHAR(10),
  category VARCHAR(50),
  has_ear_tag BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  is_protected BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. BREEDS (per species)
-- ============================================================
CREATE TABLE IF NOT EXISTS master_breeds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  species_id UUID NOT NULL REFERENCES master_species(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(species_id, name)
);

-- ============================================================
-- 3. ANIMAL CLASS TERMS (per species - Bull/Cow/Bullock etc.)
-- ============================================================
CREATE TABLE IF NOT EXISTS master_animal_classes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  species_id UUID NOT NULL REFERENCES master_species(id) ON DELETE CASCADE,
  value VARCHAR(50) NOT NULL,
  label_key VARCHAR(150),
  label VARCHAR(100),
  implied_gender VARCHAR(10) NOT NULL DEFAULT 'unknown' CHECK (implied_gender IN ('male', 'female', 'unknown')),
  can_be_pregnant BOOLEAN DEFAULT false,
  can_produce_milk BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(species_id, value)
);

-- ============================================================
-- 4. MARKETPLACE CATEGORIES
-- ============================================================
CREATE TABLE IF NOT EXISTS master_marketplace_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(50) UNIQUE NOT NULL,
  label_key VARCHAR(150),
  label VARCHAR(100),
  icon VARCHAR(10),
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  is_protected BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 5. MARKETPLACE CONDITIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS master_marketplace_conditions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(30) UNIQUE NOT NULL,
  label_key VARCHAR(150),
  label VARCHAR(100),
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_master_species_active ON master_species(is_active);
CREATE INDEX IF NOT EXISTS idx_master_breeds_species ON master_breeds(species_id);
CREATE INDEX IF NOT EXISTS idx_master_breeds_active ON master_breeds(is_active);
CREATE INDEX IF NOT EXISTS idx_master_animal_classes_species ON master_animal_classes(species_id);
CREATE INDEX IF NOT EXISTS idx_master_animal_classes_active ON master_animal_classes(is_active);
CREATE INDEX IF NOT EXISTS idx_master_mp_categories_active ON master_marketplace_categories(is_active);
CREATE INDEX IF NOT EXISTS idx_master_mp_conditions_active ON master_marketplace_conditions(is_active);

-- ============================================================
-- SEED DATA
-- ============================================================
-- Generated from the current hardcoded TypeScript arrays (frontend/src/constants/
-- speciesBreeds.ts + Marketplace.tsx's CATEGORY_KEYS) via a one-off Node script that
-- parsed the actual source AST and evaluated the literal values, guaranteeing exact
-- fidelity (51 species, 423 breeds, 37 animal-class terms, 7 marketplace categories,
-- 3 marketplace conditions) - not hand-transcribed, to eliminate transcription-error risk
-- across 400+ breed names. Existing pages therefore see IDENTICAL data immediately after
-- this migration runs; nothing changes on migration day.
-- Species (generated from SPECIES_CATEGORIES + BREED_DATABASE keys, frontend/src/constants/speciesBreeds.ts)
INSERT INTO master_species (id, code, label, icon, category, has_ear_tag, sort_order, is_active) VALUES
  (gen_random_uuid(), 'Dog', 'Dog', '🐕', 'Common Pets', false, 10, true),
  (gen_random_uuid(), 'Cat', 'Cat', '🐈', 'Common Pets', false, 20, true),
  (gen_random_uuid(), 'Rabbit', 'Rabbit', '🐰', 'Small Pets', false, 30, true),
  (gen_random_uuid(), 'Hamster', 'Hamster', '🐹', 'Small Pets', false, 40, true),
  (gen_random_uuid(), 'Guinea Pig', 'Guinea Pig', '🐾', 'Small Pets', false, 50, true),
  (gen_random_uuid(), 'Gerbil', 'Gerbil', '🐀', 'Small Pets', false, 60, true),
  (gen_random_uuid(), 'Chinchilla', 'Chinchilla', '🐭', 'Small Pets', false, 70, true),
  (gen_random_uuid(), 'Ferret', 'Ferret', '🦡', 'Small Pets', false, 80, true),
  (gen_random_uuid(), 'Hedgehog', 'Hedgehog', '🦔', 'Small Pets', false, 90, true),
  (gen_random_uuid(), 'Sugar Glider', 'Sugar Glider', '🦘', 'Small Pets', false, 100, true),
  (gen_random_uuid(), 'Parrot', 'Parrot', '🦜', 'Birds', false, 110, true),
  (gen_random_uuid(), 'Budgerigar', 'Budgerigar', '🦜', 'Birds', false, 120, true),
  (gen_random_uuid(), 'Cockatiel', 'Cockatiel', '🦜', 'Birds', false, 130, true),
  (gen_random_uuid(), 'Lovebird', 'Lovebird', '💚', 'Birds', false, 140, true),
  (gen_random_uuid(), 'Finch', 'Finch', '🐦', 'Birds', false, 150, true),
  (gen_random_uuid(), 'Canary', 'Canary', '🐦', 'Birds', false, 160, true),
  (gen_random_uuid(), 'Mynah', 'Mynah', '🐦', 'Birds', false, 170, true),
  (gen_random_uuid(), 'Pigeon', 'Pigeon', '🕊️', 'Birds', false, 180, true),
  (gen_random_uuid(), 'Bird', 'Bird', '🐦', 'Birds', false, 190, true),
  (gen_random_uuid(), 'Tortoise', 'Tortoise', '🐢', 'Reptiles', false, 200, true),
  (gen_random_uuid(), 'Turtle', 'Turtle', '🐢', 'Reptiles', false, 210, true),
  (gen_random_uuid(), 'Gecko', 'Gecko', '🦎', 'Reptiles', false, 220, true),
  (gen_random_uuid(), 'Bearded Dragon', 'Bearded Dragon', '🦎', 'Reptiles', false, 230, true),
  (gen_random_uuid(), 'Chameleon', 'Chameleon', '🦎', 'Reptiles', false, 240, true),
  (gen_random_uuid(), 'Snake', 'Snake', '🐍', 'Reptiles', false, 250, true),
  (gen_random_uuid(), 'Frog', 'Frog', '🐸', 'Amphibians', false, 260, true),
  (gen_random_uuid(), 'Axolotl', 'Axolotl', '🦎', 'Amphibians', false, 270, true),
  (gen_random_uuid(), 'Ornamental Fish', 'Ornamental Fish', '🐠', 'Ornamental Fish', false, 280, true),
  (gen_random_uuid(), 'Koi', 'Koi', '🐟', 'Ornamental Fish', false, 290, true),
  (gen_random_uuid(), 'Arowana', 'Arowana', '🐟', 'Ornamental Fish', false, 300, true),
  (gen_random_uuid(), 'Goldfish', 'Goldfish', '🐡', 'Ornamental Fish', false, 310, true),
  (gen_random_uuid(), 'Cattle', 'Cattle', '🐄', 'Livestock / Farm', true, 320, true),
  (gen_random_uuid(), 'Buffalo', 'Buffalo', '🐃', 'Livestock / Farm', true, 330, true),
  (gen_random_uuid(), 'Horse', 'Horse', '🐴', 'Livestock / Farm', true, 340, true),
  (gen_random_uuid(), 'Donkey', 'Donkey', '🫏', 'Livestock / Farm', true, 350, true),
  (gen_random_uuid(), 'Sheep', 'Sheep', '🐑', 'Livestock / Farm', true, 360, true),
  (gen_random_uuid(), 'Goat', 'Goat', '🐐', 'Livestock / Farm', true, 370, true),
  (gen_random_uuid(), 'Pig', 'Pig', '🐷', 'Livestock / Farm', true, 380, true),
  (gen_random_uuid(), 'Camel', 'Camel', '🐪', 'Livestock / Farm', true, 390, true),
  (gen_random_uuid(), 'Yak', 'Yak', '🐂', 'Livestock / Farm', true, 400, true),
  (gen_random_uuid(), 'Deer', 'Deer', '🦌', 'Livestock / Farm', true, 410, true),
  (gen_random_uuid(), 'Chicken', 'Chicken', '🐔', 'Poultry', false, 420, true),
  (gen_random_uuid(), 'Duck', 'Duck', '🦆', 'Poultry', false, 430, true),
  (gen_random_uuid(), 'Turkey', 'Turkey', '🦃', 'Poultry', false, 440, true),
  (gen_random_uuid(), 'Quail', 'Quail', '🐦', 'Poultry', false, 450, true),
  (gen_random_uuid(), 'Emu', 'Emu', '🦤', 'Poultry', true, 460, true),
  (gen_random_uuid(), 'Ostrich', 'Ostrich', '🦢', 'Poultry', true, 470, true),
  (gen_random_uuid(), 'Peacock', 'Peacock', '🦚', 'Poultry', true, 480, true),
  (gen_random_uuid(), 'Llama', 'Llama', '🦙', 'Exotic Large', true, 490, true),
  (gen_random_uuid(), 'Alpaca', 'Alpaca', '🦙', 'Exotic Large', true, 500, true),
  (gen_random_uuid(), 'Other', 'Other', '🐾', 'Other', false, 510, true)
ON CONFLICT (code) DO NOTHING;

-- Breeds (generated from BREED_DATABASE, frontend/src/constants/speciesBreeds.ts)
INSERT INTO master_breeds (id, species_id, name, sort_order, is_active) VALUES
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Indian Pariah', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Mudhol Hound', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Rajapalayam', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Kanni', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Chippiparai', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Kombai', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Bakharwal', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Rampur Greyhound', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Himalayan Sheepdog', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Labrador Retriever', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Golden Retriever', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'German Shepherd', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Beagle', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Pug', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Dachshund', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Rottweiler', 160, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Doberman Pinscher', 170, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Great Dane', 180, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Saint Bernard', 190, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Siberian Husky', 200, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Shih Tzu', 210, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Pomeranian', 220, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Cocker Spaniel', 230, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Boxer', 240, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Dalmatian', 250, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Border Collie', 260, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Maltese', 270, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Poodle', 280, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Bichon Frise', 290, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'German Spitz', 300, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Lhasa Apso', 310, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Chow Chow', 320, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Bulldog', 330, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'French Bulldog', 340, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Yorkshire Terrier', 350, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Mixed Breed', 360, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'Other', 370, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Persian', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Siamese', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Bengal', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Maine Coon', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Russian Blue', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'British Shorthair', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Scottish Fold', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Ragdoll', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Himalayan', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Turkish Angora', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Bombay', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'American Shorthair', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Abyssinian', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Burmese', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Devon Rex', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Indian Domestic', 160, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Mixed Breed', 170, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'Other', 180, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'New Zealand White', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Dutch', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Rex', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Angora', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Mini Lop', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Holland Lop', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Flemish Giant', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Lionhead', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Himalayan', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Mixed Breed', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Rabbit'), 'Other', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Syrian (Golden)', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Dwarf Campbell', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Dwarf Winter White', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Roborovski', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Chinese', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hamster'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'American', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Abyssinian', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Peruvian', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Silkie', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Teddy', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Texel', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Mixed', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Guinea Pig'), 'Other', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gerbil'), 'Mongolian', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gerbil'), 'Fat-tailed', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gerbil'), 'Mixed', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gerbil'), 'Other', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'Standard Grey', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'White', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'Beige', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'Black Velvet', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'Violet', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chinchilla'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Sable', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Albino', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Dark-eyed White', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Silver', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Cinnamon', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ferret'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hedgehog'), 'African Pygmy', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hedgehog'), 'European', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hedgehog'), 'Long-eared', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hedgehog'), 'Mixed', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Hedgehog'), 'Other', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sugar Glider'), 'Classic Grey', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sugar Glider'), 'Leucistic', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sugar Glider'), 'Albino', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sugar Glider'), 'Black Beauty', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sugar Glider'), 'Mixed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sugar Glider'), 'Other', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'African Grey', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Blue and Gold Macaw', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Green Wing Macaw', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Scarlet Macaw', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Cockatoo', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Yellow-naped Amazon', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Blue-fronted Amazon', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Eclectus', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Sun Conure', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Green Cheek Conure', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Caique', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Alexandrine Parakeet', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Rose-ringed Parakeet', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Mixed', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Parrot'), 'Other', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'English Budgie', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'American Budgie', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'Australian Budgie', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'Lutino', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'Albino', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'Pied', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'Mixed', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Budgerigar'), 'Other', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Normal Grey', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Lutino', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Pearl', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Cinnamon', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Pied', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Whiteface', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Mixed', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cockatiel'), 'Other', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Peach-faced', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Fischer''s', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Black-masked', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Nyasa', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Black-cheeked', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Lovebird'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Zebra Finch', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Society Finch', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Gouldian Finch', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Java Sparrow', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Star Finch', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Finch'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Yorkshire', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Border', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Roller', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Red Factor', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Gloster', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Canary'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Mynah'), 'Common Hill Mynah', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Mynah'), 'Bank Mynah', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Mynah'), 'Jungle Mynah', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Mynah'), 'Mixed', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Mynah'), 'Other', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Fantail', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Jacobin', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Tumbler', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'King', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Racing Homer', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Indian Fantail', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Mixed', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pigeon'), 'Other', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Bird'), 'Mixed / Unknown', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Bird'), 'Other', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Indian Star Tortoise', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Russian Tortoise', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Hermann''s Tortoise', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Sulcata', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Red-footed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Tortoise'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turtle'), 'Red-eared Slider', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turtle'), 'Painted Turtle', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turtle'), 'Map Turtle', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turtle'), 'Box Turtle', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turtle'), 'Mixed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turtle'), 'Other', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'Leopard Gecko', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'Crested Gecko', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'African Fat-tailed', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'Tokay', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'Day Gecko', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Gecko'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Bearded Dragon'), 'Inland/Central', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Bearded Dragon'), 'Rankin''s Dragon', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Bearded Dragon'), 'Mixed', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Bearded Dragon'), 'Other', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chameleon'), 'Veiled', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chameleon'), 'Panther', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chameleon'), 'Jackson''s', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chameleon'), 'Fischer''s', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chameleon'), 'Mixed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chameleon'), 'Other', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'Ball Python', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'Corn Snake', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'King Snake', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'Milk Snake', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'Boa Constrictor', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Snake'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Frog'), 'African Dwarf', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Frog'), 'Pacman (Horned)', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Frog'), 'Tree Frog', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Frog'), 'White''s Tree Frog', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Frog'), 'Mixed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Frog'), 'Other', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Wild Type', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Leucistic', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Golden Albino', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Melanoid', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Axanthic', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Axolotl'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Betta', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Guppy', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Mollies', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Platy', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Swordtail', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Tetra', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Angelfish', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Discus', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Cichlid', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Clownfish', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Mixed', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ornamental Fish'), 'Other', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Kohaku', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Sanke', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Showa', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Bekko', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Asagi', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Ogon', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Butterfly Koi', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Mixed', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Koi'), 'Other', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Silver', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Golden', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Red', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Black', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Pearl', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Arowana'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Common', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Comet', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Fantail', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Oranda', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Ryukin', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Black Moor', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Telescope', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Bubble Eye', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Mixed', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goldfish'), 'Other', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Gir', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Sahiwal', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Red Sindhi', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Tharparkar', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Ongole', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Hallikar', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Khillari', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Deoni', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Kangayam', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Umblachery', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Malnad Gidda', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Punganur', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Vechur', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Hariana', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Rathi', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Holstein Friesian (HF)', 160, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Jersey', 170, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Brown Swiss', 180, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Simmental', 190, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Mixed Breed', 200, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'Other', 210, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Murrah', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Surti', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Mehsana', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Jaffarabadi', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Nili-Ravi', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Pandharpuri', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Marathwadi', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Nagpuri', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Toda (Nilgiri)', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Mixed', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'Other', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Marwari', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Kathiawari', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Manipuri Pony', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Bhutia', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Spiti', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Zanskari', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Thoroughbred', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Arabian', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Quarter Horse', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Warmblood', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Standardbred', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Mixed Breed', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Horse'), 'Other', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Donkey'), 'Indian Donkey', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Donkey'), 'Halari', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Donkey'), 'Spiti', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Donkey'), 'Mixed', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Donkey'), 'Other', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Nellore', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Deccani', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Mandya', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Bellary', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Madras Red', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Coimbatore', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Mecheri', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Ramnad White', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Vembur', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Nilgiri', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Korriedale', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Garole', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Merino', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Suffolk', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Rambouillet', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Mixed Breed', 160, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'Other', 170, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Jamunapari', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Barbari', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Sirohi', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Black Bengal', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Osmanabadi', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Salem Black', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Malabari', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Sangamneri', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Ganjam', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Kanniadu', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Boer', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Alpine', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Saanen', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Nubian', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Angora', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Mixed Breed', 160, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'Other', 170, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Desi (Indigenous)', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Ghungroo', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Niang Megha', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Yorkshire (Large White)', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Landrace', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Duroc', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Hampshire', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Berkshire', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Mixed Breed', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'Other', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Camel'), 'Dromedary (One-humped)', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Camel'), 'Bactrian (Two-humped)', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Camel'), 'Mixed', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Camel'), 'Other', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Yak'), 'Domestic Yak', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Yak'), 'Mixed', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Yak'), 'Other', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Deer'), 'Spotted Deer (Chital)', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Deer'), 'Sambhar', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Deer'), 'Barking Deer (Muntjac)', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Deer'), 'Mixed', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Deer'), 'Other', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Aseel', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Kadaknath', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Ghagus', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Naked Neck', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Kalinga Brown', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Vanaraja', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Grampriya', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Nicobari', 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Broiler', 90, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'White Leghorn', 100, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Rhode Island Red', 110, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Plymouth Rock', 120, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Sussex', 130, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Australorp', 140, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Mixed Breed', 150, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Chicken'), 'Other', 160, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Indian Runner', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Khaki Campbell', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Pekin', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Muscovy', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Rouen', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Mixed', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Duck'), 'Other', 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turkey'), 'Broad-breasted White', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turkey'), 'Bronze', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turkey'), 'Bourbon Red', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turkey'), 'Narragansett', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turkey'), 'Mixed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Turkey'), 'Other', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Quail'), 'Japanese', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Quail'), 'Bobwhite', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Quail'), 'California', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Quail'), 'Coturnix', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Quail'), 'Mixed', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Quail'), 'Other', 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Emu'), 'Australian Emu', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Emu'), 'Other', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ostrich'), 'Common Ostrich', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Ostrich'), 'Other', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Peacock'), 'Indian Peafowl (Blue)', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Peacock'), 'White Peafowl', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Peacock'), 'Green Peafowl', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Peacock'), 'Mixed', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Peacock'), 'Other', 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Llama'), 'Suri', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Llama'), 'Huacaya', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Llama'), 'Mixed', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Llama'), 'Other', 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Alpaca'), 'Suri', 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Alpaca'), 'Huacaya', 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Alpaca'), 'Mixed', 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Alpaca'), 'Other', 40, true)
ON CONFLICT (species_id, name) DO NOTHING;

-- Animal classes (generated from ANIMAL_CLASS_TERMS, frontend/src/constants/speciesBreeds.ts)
INSERT INTO master_animal_classes (id, species_id, value, label_key, implied_gender, can_be_pregnant, can_produce_milk, sort_order, is_active) VALUES
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_bull', 'animalClass.cattle_bull', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_cow', 'animalClass.cattle_cow', 'female', true, true, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_calf', 'animalClass.cattle_calf', 'unknown', false, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_bull_calf', 'animalClass.cattle_bull_calf', 'male', false, false, 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_heifer_calf', 'animalClass.cattle_heifer_calf', 'female', false, false, 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_heifer', 'animalClass.cattle_heifer', 'female', true, false, 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_bullock', 'animalClass.cattle_bullock', 'male', false, false, 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cattle'), 'cattle_steer', 'animalClass.cattle_steer', 'male', false, false, 80, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_bull', 'animalClass.buffalo_bull', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_cow', 'animalClass.buffalo_cow', 'female', true, true, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_calf', 'animalClass.buffalo_calf', 'unknown', false, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_bull_calf', 'animalClass.buffalo_bull_calf', 'male', false, false, 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_heifer_calf', 'animalClass.buffalo_heifer_calf', 'female', false, false, 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_heifer', 'animalClass.buffalo_heifer', 'female', true, false, 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Buffalo'), 'buffalo_bullock', 'animalClass.buffalo_bullock', 'male', false, false, 70, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'sheep_ram', 'animalClass.sheep_ram', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'sheep_ewe', 'animalClass.sheep_ewe', 'female', true, true, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'sheep_lamb', 'animalClass.sheep_lamb', 'unknown', false, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'sheep_ram_lamb', 'animalClass.sheep_ram_lamb', 'male', false, false, 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'sheep_ewe_lamb', 'animalClass.sheep_ewe_lamb', 'female', false, false, 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Sheep'), 'sheep_wether', 'animalClass.sheep_wether', 'male', false, false, 60, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'goat_buck', 'animalClass.goat_buck', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'goat_doe', 'animalClass.goat_doe', 'female', true, true, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'goat_buckling', 'animalClass.goat_buckling', 'male', false, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'goat_goatling', 'animalClass.goat_goatling', 'female', true, false, 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Goat'), 'goat_kid', 'animalClass.goat_kid', 'unknown', false, false, 50, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'pig_boar', 'animalClass.pig_boar', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'pig_sow', 'animalClass.pig_sow', 'female', true, false, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'pig_gilt', 'animalClass.pig_gilt', 'female', true, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Pig'), 'pig_barrow', 'animalClass.pig_barrow', 'male', false, false, 40, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'dog_male', 'animalClass.dog_male', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'dog_bitch', 'animalClass.dog_bitch', 'female', true, false, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Dog'), 'dog_pup', 'animalClass.dog_pup', 'unknown', false, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'cat_tom', 'animalClass.cat_tom', 'male', false, false, 10, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'cat_queen', 'animalClass.cat_queen', 'female', true, false, 20, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'cat_kitten', 'animalClass.cat_kitten', 'unknown', false, false, 30, true),
  (gen_random_uuid(), (SELECT id FROM master_species WHERE code = 'Cat'), 'cat_neuter', 'animalClass.cat_neuter', 'unknown', false, false, 40, true)
ON CONFLICT (species_id, value) DO NOTHING;

-- Marketplace categories (generated from CATEGORY_KEYS, frontend/src/pages/Marketplace.tsx - skips the blank '' "all" filter entry)
INSERT INTO master_marketplace_categories (id, code, label_key, sort_order, is_active, is_protected) VALUES
  (gen_random_uuid(), 'animal', 'marketplace.categories.animals', 10, true, true),
  (gen_random_uuid(), 'feed', 'marketplace.categories.feed', 20, true, false),
  (gen_random_uuid(), 'equipment', 'marketplace.categories.equipment', 30, true, false),
  (gen_random_uuid(), 'medicine', 'marketplace.categories.medicine', 40, true, false),
  (gen_random_uuid(), 'semen_embryo', 'marketplace.categories.semenEmbryo', 50, true, false),
  (gen_random_uuid(), 'service', 'marketplace.categories.services', 60, true, false),
  (gen_random_uuid(), 'other', 'marketplace.categories.other', 70, true, false)
ON CONFLICT (code) DO NOTHING;

-- Marketplace conditions (3 fixed values from Marketplace.tsx sell-form <option>s)
INSERT INTO master_marketplace_conditions (id, code, label_key, sort_order, is_active) VALUES
  (gen_random_uuid(), 'new', 'marketplace.conditionLabel.healthy', 10, true),
  (gen_random_uuid(), 'used', 'marketplace.conditionLabel.fair', 20, true),
  (gen_random_uuid(), 'refurbished', 'marketplace.conditionLabel.underTreatment', 30, true)
ON CONFLICT (code) DO NOTHING;
