import { test, expect } from './fixtures'
import { loginAs } from './fixtures'
import { USERS } from './constants'

/**
 * AUTO-GENERATED TEST STUBS
 *
 * These tests were auto-generated by generate-tests.js
 * for routes that don't have existing test coverage.
 *
 * Generated: 2026-06-23T10:21:25.249Z
 *
 * TODO: Expand these stubs with specific assertions for each page.
 */

test.describe('Auto-Discovered — /forgot-password', () => {
  test('should load /forgot-password without crash', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await loginAs(page, 'admin')
    await page.goto('/forgot-password')
    await page.waitForLoadState('domcontentloaded')
    await expect(page).not.toHaveURL(/\/login/)
    const content = await page.textContent('body')
    expect(content!.length).toBeGreaterThan(0)
    await context.close()
  })
})

test.describe('Auto-Discovered — /reset-password', () => {
  test('should load /reset-password without crash', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await loginAs(page, 'admin')
    await page.goto('/reset-password')
    await page.waitForLoadState('domcontentloaded')
    await expect(page).not.toHaveURL(/\/login/)
    const content = await page.textContent('body')
    expect(content!.length).toBeGreaterThan(0)
    await context.close()
  })
})

