#!/usr/bin/env node

/**
 * VetCare E2E - Auto-Discovery Test Generator
 *
 * Scans App.tsx for all routes and Navigation.tsx for menu items,
 * then generates test stubs for any route that doesn't have a test.
 *
 * Usage:
 *   node e2e/generate-tests.js          - show report
 *   node e2e/generate-tests.js --write  - write missing test file
 *
 * Run this after adding new pages/routes to auto-create E2E test coverage.
 * Can be hooked into CI or pre-commit to enforce test coverage for new routes.
 */

const fs = require('fs')
const path = require('path')

const FRONTEND_DIR = path.resolve(__dirname, '..')
const APP_TSX = path.join(FRONTEND_DIR, 'src', 'App.tsx')
const NAV_TSX = path.join(FRONTEND_DIR, 'src', 'components', 'Navigation.tsx')
const E2E_DIR = path.join(FRONTEND_DIR, 'e2e')

// ── Parse all routes from App.tsx ───────────────────────────
function parseRoutes() {
  const content = fs.readFileSync(APP_TSX, 'utf-8')
  const routes = []

  // Match <Route path="/some-path" ...>
  const routeRegex = /<Route\s+path="([^"]+)"/g
  let match
  while ((match = routeRegex.exec(content)) !== null) {
    const routePath = match[1]
    // Skip redirects (<Navigate>) and catch-all
    if (routePath === '*') continue

    // Determine route type
    const lineStart = content.lastIndexOf('\n', match.index) + 1
    const lineEnd = content.indexOf('\n', match.index)
    const line = content.substring(lineStart, lineEnd)

    let type = 'public'
    if (line.includes('RoleRoute')) type = 'role-protected'
    else if (line.includes('ProtectedRoute')) type = 'protected'
    else if (line.includes('PublicOnlyRoute')) type = 'public-only'

    // Check for Navigate (redirect routes)
    if (line.includes('<Navigate')) {
      type = 'redirect'
    }

    // Extract path key from RoleRoute
    let permPath = routePath
    const pathMatch = line.match(/path="([^"]+)"[^>]*>.*<RoleRoute\s+path="([^"]+)"/)
    if (!pathMatch) {
      const rolePathMatch = line.match(/RoleRoute\s+path="([^"]+)"/)
      if (rolePathMatch) permPath = rolePathMatch[1]
    }

    routes.push({
      path: routePath,
      type,
      permPath,
      hasParams: routePath.includes(':'),
    })
  }

  return routes
}

// ── Parse nav items from Navigation.tsx ─────────────────────
function parseNavItems() {
  const content = fs.readFileSync(NAV_TSX, 'utf-8')
  const items = []

  // Match menu item objects: { id: '...', ... path: '...', roles: [...], section: '...' }
  const itemRegex = /\{\s*id:\s*'([^']+)'.*?path:\s*'([^']+)'.*?roles:\s*\[([^\]]+)\].*?section:\s*'([^']+)'/gs
  let match
  while ((match = itemRegex.exec(content)) !== null) {
    const [, id, navPath, rolesStr, section] = match
    const roles = rolesStr.split(',').map(r => r.trim().replace(/'/g, ''))
    items.push({ id, path: navPath, roles, section })
  }

  return items
}

// ── Scan existing test files for covered routes ─────────────
function findCoveredRoutes() {
  const covered = new Set()
  const testFiles = fs.readdirSync(E2E_DIR).filter(f => f.endsWith('.spec.ts'))

  for (const file of testFiles) {
    const content = fs.readFileSync(path.join(E2E_DIR, file), 'utf-8')

    // Match page.goto('/some-path') patterns
    const gotoRegex = /page\.goto\(['"`]([^'"`]+)['"`]\)/g
    let match
    while ((match = gotoRegex.exec(content)) !== null) {
      covered.add(match[1])
    }

    // Match toHaveURL patterns
    const urlRegex = /toHaveURL\(.*?\/([a-z0-9\-\/]+)/gi
    while ((match = urlRegex.exec(content)) !== null) {
      covered.add('/' + match[1].replace(/\\\//g, '/'))
    }

    // Match route strings in ROUTE_ROLES or test data
    const routeStrRegex = /'(\/[a-z0-9\-\/]+)'/g
    while ((match = routeStrRegex.exec(content)) !== null) {
      covered.add(match[1])
    }
  }

  return covered
}

// ── Generate test stub for uncovered routes ─────────────────
function generateTestStub(uncoveredRoutes, navItems) {
  const roleMap = {}
  for (const item of navItems) {
    roleMap[item.path] = item.roles
  }

  let stub = `import { test, expect } from './fixtures'
import { loginAs } from './fixtures'
import { USERS } from './constants'

/**
 * AUTO-GENERATED TEST STUBS
 *
 * These tests were auto-generated by generate-tests.js
 * for routes that don't have existing test coverage.
 *
 * Generated: ${new Date().toISOString()}
 *
 * TODO: Expand these stubs with specific assertions for each page.
 */

`

  const ROLE_USER_MAP = {
    admin: 'admin',
    veterinarian: 'vet1',
    pet_owner: 'petOwner1',
    farmer: 'farmer1',
  }

  for (const route of uncoveredRoutes) {
    const roles = roleMap[route.path] || ['admin']
    const primaryRole = roles[0]
    const userKey = ROLE_USER_MAP[primaryRole] || 'admin'
    const pageName = route.path.split('/').filter(Boolean).join('-') || 'root'

    stub += `test.describe('Auto-Discovered - ${route.path}', () => {
  test('should load ${route.path} without crash', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await loginAs(page, '${userKey}')
    await page.goto('${route.path}')
    await page.waitForLoadState('domcontentloaded')
    await expect(page).not.toHaveURL(/\\/login/)
    const content = await page.textContent('body')
    expect(content!.length).toBeGreaterThan(0)
    await context.close()
  })
})

`
  }

  return stub
}

// ── Main ────────────────────────────────────────────────────
function main() {
  const writeMode = process.argv.includes('--write')

  console.log('🔍 VetCare E2E Test Auto-Discovery')
  console.log('=' .repeat(50))

  // 1. Parse all routes
  const routes = parseRoutes()
  console.log(`\n📎 Found ${routes.length} routes in App.tsx`)

  // 2. Parse nav items
  const navItems = parseNavItems()
  console.log(`📎 Found ${navItems.length} nav items in Navigation.tsx`)

  // 3. Find covered routes
  const covered = findCoveredRoutes()
  console.log(`✅ Found ${covered.size} routes covered by existing tests`)

  // 4. Find uncovered routes
  const testableRoutes = routes.filter(r =>
    r.type !== 'redirect' &&
    !r.hasParams &&  // Skip parameterized routes (need specific IDs)
    !covered.has(r.path)
  )

  console.log(`\n${'─'.repeat(50)}`)

  if (testableRoutes.length === 0) {
    console.log('\n🎉 ALL routes have test coverage!')
    console.log('   No new test stubs needed.')
    process.exit(0)
  }

  console.log(`\n⚠️  ${testableRoutes.length} routes WITHOUT test coverage:`)
  for (const r of testableRoutes) {
    console.log(`   ${r.type.padEnd(16)} ${r.path}`)
  }

  if (writeMode) {
    const stubContent = generateTestStub(testableRoutes, navItems)
    const outputFile = path.join(E2E_DIR, 'auto-discovered.spec.ts')
    fs.writeFileSync(outputFile, stubContent)
    console.log(`\n✅ Generated: e2e/auto-discovered.spec.ts`)
    console.log(`   Contains ${testableRoutes.length} test stubs.`)
    console.log('   Review and expand with specific assertions.')
  } else {
    console.log('\n💡 Run with --write to generate test stubs:')
    console.log('   node e2e/generate-tests.cjs --write')
  }

  // 5. Coverage summary
  const totalTestable = routes.filter(r => r.type !== 'redirect' && !r.hasParams).length
  const coveredCount = totalTestable - testableRoutes.length
  const pct = ((coveredCount / totalTestable) * 100).toFixed(1)
  console.log(`\n📊 Route Coverage: ${coveredCount}/${totalTestable} (${pct}%)`)

  // Exit with failure in non-write mode (CI will catch this)
  if (!writeMode) {
    process.exit(1)
  }
}

main()
